name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: dylan-lang/install-opendylan@v1

      - name: Build strings-test-suite-app
        run: ./dylan-compiler -build strings-test-suite-app

      - name: Run strings-test-suite-app
        run: _build/bin/strings-test-suite-app
